### ISSUE TITLE
Opkobling med FDW i Postgres

### ISSUE THREAD

**Issue by Ellebjerg** [mapcentia/FKGuploader#1]
Har I erfaring med brug af Foreign Data Wrapper i Postgres til at koble op imod Mapcentia FKG?

Jeg har ingen problemer med at oprette en FDW Server i PG, men jeg får ikke oprettet nogen tabeller, selv om jeg får meddelelse om, at min query er afviklet med succes.

Hvis I har erfaring med brug af FDW op imod pg, vil jeg blive glad for et eksempelscript, gerne baseret på t_5710_born_skole_gis, som jeg aktuelt bokser med at få til at virke.

Vh Lars

**Comment by Ellebjerg** [comment]
Jeg har fået hul igennem, om end det går meget langsomt.

**Comment by mapcentia** [comment]
@Ellebjerg Husk at sætte `extensions` og `fetch_size` options ala:

`CREATE SERVER min_server FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host 'fkg.mapcentia.com', dbname 'dk', port '5432', extensions 'postgis', fetch_size '10000', updatable 'false');`

**Comment by Ellebjerg** [comment]
Tak, jeg laver en postgres_fdw i stedet for en wfs. Det burde fungere bedre.
