### ISSUE TITLE
Er servicen nede?

### ISSUE THREAD

**Issue by Ellebjerg** [mapcentia/FKGuploader#2]
Når jeg prøver at tilgå https://fkg-kort.mapcentia.com/app/fkg/fkg/, står siden bare og loader kontinuerligt, og min WFS-datasource i Spatial Suite, som virkede fint for et par dage siden, returnerer en NullPointerException.
Er jeres service nede?
Vh Lars

**Comment by Ellebjerg** [comment]
Om igen. Jeg kan se, at servicen ikke er nede, da jeg kan komme til den ad andre veje i Spatial Suite, så mit problem der må komme et andet sted fra. Men jeg kan stadig ikke tilgå https://fkg-kort.mapcentia.com/app/fkg/fkg/.

**Comment by mapcentia** [comment]
@Ellebjerg Jeg kan konstatere at det er kort app'en, som ikke virker. Jeg kigger på det. I mellemtiden kan den gamle viewer benyttes: https://fkg.mapcentia.com/apps/viewer/fkg/fkg

**Comment by Ellebjerg** [comment]
Jeg kan også konstatere, at jeres certifikat ikke er opdateret. I hvert fald får jeg en over nallerne af både Chrome og Postgres, når jeg prøver at tilgå med https. Det virker fint med http, men da I selv angiver https-links, er det måske ikke så heldigt.

**Comment by mapcentia** [comment]
@Ellebjerg Kører igen https://fkg-kort.mapcentia.com/app/fkg/fkg/
